const ACTION_TYPE = {
	SET_CURRENT_PLAYER: 'SET_CURRENT_PLAYER',
	SET_SCORE_X_PLAYER: 'SET_SCORE_X_PLAYER',
	SET_SCORE_O_PLAYER: 'SET_SCORE_O_PLAYER',
	RESTART_GAME: 'RESTART_GAME',
};
export default ACTION_TYPE;
